# Global settings
secret_key = "your-secret-key-here"
reload_interval = 30

[deploy]

[deploy."someusername/some-repo#main"]
service_name = "some-service-1"

[deploy."someusername/some-repo#develop"]
service_name = "some-service-2"

[deploy."myorg/frontend#production"]
service_name = "some-serv-3"

[deploy."myorg/backend#staging"]
service_name = "some-serv-4"